import type { Signal, Company } from "@shared/schema";
import type { GeneratedArticle } from "./article-generator";
import { generateImageBuffer } from "./replit_integrations/image/client";
import { openai } from "./replit_integrations/image/client";
import fs from "fs";
import path from "path";

export interface MediaSitePayload {
  headline: string;
  subheadline: string;
  body: string;
  keyTakeaways: string[];
  seoDescription: string;
  tags: string[];
  author: string;
  imageUrl: string;
  imageCredit?: string;
  signal: {
    id: number;
    type: string;
    relevanceScore: number;
    sourceName: string | null;
    sourceUrl: string | null;
  };
  company: {
    id: number;
    name: string;
    industry: string | null;
  } | null;
  generatedAt: string;
}

export interface MediaSitePublishResult {
  success: boolean;
  error?: string;
  warning?: string;
  articleId?: string;
  articleUrl?: string;
}

const stockImages: Record<string, string[]> = {
  "Poultry": [
    "poultry_001.jpg",
    "poultry_002.jpg",
    "poultry_003.jpg",
  ],
  "Feed": [
    "feed_001.jpg",
    "feed_002.jpg",
    "feed_003.jpg",
  ],
  "Pet Food": [
    "pet_food_001.jpg",
    "pet_food_002.jpg",
    "pet_food_003.jpg",
  ],
};

export function selectStockImage(signal: Signal, company: Company | null, baseUrl: string): string {
  const industry = company?.industry || "Poultry";
  const images = stockImages[industry] || stockImages["Poultry"];
  const selectedImage = images[signal.id % images.length];
  return `${baseUrl}/stock-images/${selectedImage}`;
}

export async function generateAIImage(
  signal: Signal,
  company: Company | null,
  baseUrl: string
): Promise<{ imageUrl: string; credit: string } | null> {
  try {
    const industry = company?.industry || "business";
    const companyName = company?.name || "company";
    const signalType = signal.type.replace(/_/g, " ");
    
    const promptContent = signal.title + (signal.summary ? `. ${signal.summary}` : "");
    
    const promptRequest = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        {
          role: "system",
          content: `You create concise image generation prompts for news articles about ${industry}. Generate a professional, editorial-style image prompt. Focus on abstract business imagery, industry themes, or symbolic representations. Never include text, logos, or specific people's faces. Keep prompts under 100 words.`
        },
        {
          role: "user",
          content: `Create an image prompt for an article about: ${promptContent}\n\nCompany: ${companyName}\nSignal type: ${signalType}\nIndustry: ${industry}`
        }
      ],
      max_tokens: 150,
    });

    const imagePrompt = promptRequest.choices[0]?.message?.content || 
      `Professional ${industry} business scene, modern corporate setting, editorial photography style`;

    console.log("Generating AI image with prompt:", imagePrompt);

    const imageBuffer = await generateImageBuffer(
      `Editorial news photo style: ${imagePrompt}. Professional, high-quality, suitable for business publication. No text or logos.`,
      "1024x1024"
    );

    const imagesDir = path.resolve(process.cwd(), "public/generated-images");
    if (!fs.existsSync(imagesDir)) {
      fs.mkdirSync(imagesDir, { recursive: true });
    }

    const filename = `ai-image-${signal.id}-${Date.now()}.png`;
    const filePath = path.join(imagesDir, filename);
    fs.writeFileSync(filePath, imageBuffer);

    const imageUrl = `${baseUrl}/generated-images/${filename}`;

    return {
      imageUrl,
      credit: "Image generated by AI"
    };
  } catch (error) {
    console.error("Error generating AI image:", error);
    return null;
  }
}

export function buildMediaSitePayload(
  article: GeneratedArticle,
  signal: Signal,
  company: Company | null,
  imageUrl: string,
  imageCredit?: string
): MediaSitePayload {
  const aiAnalysis = signal.aiAnalysis as { relevanceScore?: number } | null;
  const relevanceScore = aiAnalysis?.relevanceScore || 50;

  return {
    headline: article.headline,
    subheadline: article.subheadline,
    body: article.body + (article.sourceAttribution ? `\n\n${article.sourceAttribution}` : ""),
    keyTakeaways: article.keyTakeaways,
    seoDescription: article.seoDescription,
    tags: article.suggestedTags || [],
    author: process.env.MEDIA_SITE_AUTHOR || "Your Publication Staff",
    imageUrl,
    imageCredit,
    signal: {
      id: signal.id,
      type: signal.type,
      relevanceScore: typeof relevanceScore === "number" ? relevanceScore : 50,
      sourceName: signal.sourceName,
      sourceUrl: signal.sourceUrl,
    },
    company: company
      ? {
          id: company.id,
          name: company.name,
          industry: company.industry,
        }
      : null,
    generatedAt: new Date().toISOString(),
  };
}

export async function publishToMediaSite(
  payload: MediaSitePayload
): Promise<MediaSitePublishResult> {
  const mediaSiteUrl = process.env.MEDIA_SITE_URL;
  const mediaSiteApiKey = process.env.MEDIA_SITE_API_KEY;

  if (!mediaSiteUrl) {
    return {
      success: false,
      error: "MEDIA_SITE_URL environment variable is not configured",
    };
  }

  const apiUrl = `${mediaSiteUrl.replace(/\/$/, "")}/api/articles/receive`;

  try {
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      "X-Source": "signalwatch-platform",
    };

    if (mediaSiteApiKey) {
      headers["X-API-Key"] = mediaSiteApiKey;
    }

    const response = await fetch(apiUrl, {
      method: "POST",
      headers,
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorText = await response.text();
      let errorMessage = `Media site API error: ${response.status}`;
      try {
        const errorJson = JSON.parse(errorText);
        errorMessage = errorJson.message || errorJson.error || errorMessage;
      } catch {
        errorMessage = errorText || errorMessage;
      }
      return { success: false, error: errorMessage };
    }

    const result = await response.json();
    
    const articleId = result.id?.toString() || result.articleId?.toString();
    const articleUrl = result.url || result.articleUrl;
    
    if (!articleId && !articleUrl) {
      console.warn("Media site returned success but no article ID or URL - article may not have been saved");
      return {
        success: true,
        articleId: undefined,
        articleUrl: undefined,
        warning: "Article was accepted but no confirmation ID was returned. Please verify on the media site.",
      };
    }

    return {
      success: true,
      articleId,
      articleUrl,
    };
  } catch (error) {
    console.error("Media site publish error:", error);
    return {
      success: false,
      error: error instanceof Error ? error.message : "Failed to connect to media site",
    };
  }
}
